server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
  devtools:
    restart:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/back
    username: postgres
    password: 1234
  liquibase:
    change-log: classpath:db/changelog.yml